name: Switch Node version
on: 
  pull_request:

jobs:
  run-npm-test:
    runs-on: ubuntu-latest
    env: 
        NODE_VERSION: 20
    steps:
        - name: checkout
          uses: actions/checkout@v6
        - name : setup node
          uses: actions/setup-node@v6
          with:
            node-version: '$NODE_VERSION'
        - name : node version
          shell : bash
          run: |
            node -v
        - name: run test
          shell: bash
          run: |
            npm install
            npm test