name: npm test from reusable

on:
  workflow_dispatch:
    inputs:
      version:
        default: 'lts'
        type: choice
        options:
          - 'lts'
          - '20'
          - '22'
  push:

jobs:
  test:
    uses: thibautscholaert/github-actions-training/.github/workflows/test.yaml@main 
    with:
      version: '20'
